ALTER TABLE EXT_MODULL DROP COLUMN TOTAL;
ALTER TABLE EXT_MODULL DROP COLUMN TOTAL_COST;
ALTER TABLE EXT_MODULL DROP COLUMN COUNT;

ALTER TABLE EXT_CONTRACTMODULL ADD COLUMN COUNT varchar(10);
ALTER TABLE EXT_CONTRACTMODULL ADD COLUMN TOTAL_COST varchar(25);